name: Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest

    steps:
    - name: Create Folder
      run: |
        sleep 60
        mkdir actions-testing